name: climaax_droughts

channels:
    - conda-forge

dependencies:
        - python=3.11
        - gdal
        - numpy
        - rasterio
        - matplotlib
        - tqdm
        - pip
        - jupyterlab
        - pyproj
        - xarray
        - rioxarray
        - scipy
        - cartopy
        - pandas
        - ipywidgets
        - ipympl
        - nbmake
        - pytest
        - pip:
            - netcdf4
            - jupyterlab_myst
   
          
